#!/usr/bin/env python3
"""Regenerate skills/registry.yaml as a mirror of hub/registry.yaml.

hub/registry.yaml is the source of truth for the catalog. skills/registry.yaml
is kept as a generated copy for 60 days post `hub-v2-manifest-state-profiles`
apply so external tools that pinned the old path keep working.

On POSIX systems, skills/registry.yaml MAY be a symlink to hub/registry.yaml
instead of a copy — both are valid. This script prefers a regenerated copy
because (a) it works on Windows where symlinks need special permissions, and
(b) git treats the copy identically across platforms.

Usage:
    python tools/regenerate-skills-registry-mirror.py [--check]

    --check  Exit 1 if the mirror is out of date instead of regenerating
             (useful for CI / pre-commit).

Exit codes:
    0  mirror up to date (or regenerated successfully)
    1  mirror was stale (--check mode) — re-run without --check to fix
    2  usage error (source file missing, write failed)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "hub" / "registry.yaml"
MIRROR = REPO_ROOT / "skills" / "registry.yaml"

MIRROR_HEADER = """\
# =====================================================================
# DO NOT EDIT — GENERATED MIRROR
# =====================================================================
# This file is a generated copy of `hub/registry.yaml`, kept here for
# backward compatibility during a 60-day migration window after the
# `hub-v2-manifest-state-profiles` change applied.
#
# Source of truth:  hub/registry.yaml
# Regenerated by:   tools/regenerate-skills-registry-mirror.py
# CI guard:         .github/workflows/validate-registry.yml
#
# Any edits here will be overwritten. Edit hub/registry.yaml instead.
# This mirror will be removed by a follow-up cleanup change ~2026-07-22.
# =====================================================================

"""


def _strip_existing_header(content: str) -> str:
    """Drop a previously written DO NOT EDIT block (between the matching ===
    fences) so the regenerated mirror doesn't keep accumulating headers."""
    lines = content.splitlines(keepends=True)
    if not lines or not lines[0].startswith("# ="):
        return content
    # Skip until the second "# =====" closing fence, then any blank lines.
    fence_count = 0
    i = 0
    while i < len(lines):
        if lines[i].startswith("# ="):
            fence_count += 1
            i += 1
            if fence_count == 2:
                break
        else:
            i += 1
    while i < len(lines) and lines[i].strip() in ("", "#"):
        i += 1
    return "".join(lines[i:])


def render_mirror() -> str:
    """Return the desired content of skills/registry.yaml derived from the source."""
    if not SOURCE.exists():
        raise FileNotFoundError(f"source not found: {SOURCE}")
    source_text = SOURCE.read_text(encoding="utf-8")
    body = _strip_existing_header(source_text)
    return MIRROR_HEADER + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate skills/registry.yaml mirror.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the mirror is stale instead of regenerating.",
    )
    args = parser.parse_args(argv)

    try:
        expected = render_mirror()
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    actual = MIRROR.read_text(encoding="utf-8") if MIRROR.exists() else ""

    if expected == actual:
        print(f"mirror up to date: {MIRROR.relative_to(REPO_ROOT)}")
        return 0

    if args.check:
        print(
            f"error: {MIRROR.relative_to(REPO_ROOT)} is out of date with "
            f"{SOURCE.relative_to(REPO_ROOT)}. "
            f"Run: python tools/regenerate-skills-registry-mirror.py",
            file=sys.stderr,
        )
        return 1

    MIRROR.parent.mkdir(parents=True, exist_ok=True)
    MIRROR.write_text(expected, encoding="utf-8")
    print(f"regenerated {MIRROR.relative_to(REPO_ROOT)} from {SOURCE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
